name: Crawler Demo Action
run-name: Crawler Demo Action

# 觸發此 action 的時機
on:
  schedule:
    - cron: "55 12 * * *"  # UTC 每天下午 12:55 執行此 action（等同於台灣晚上 8:55 執行）
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  crawler-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install Python Dependency
        run: pip3 install requests
      - name: Install Python bs
        run: pip3 install bs4
      - name: Install Python pandas
        run: pip3 install pandas
      - name: Run crawler.py  # 前面都是在安裝 Python 環境，這裡才是真的去執行 crawler.py 的程式
        run: python .github/workflows/main.py
      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add . && git commit -m "daily crawl" || echo "No changes"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/samu3306/mid.git
          git push origin HEAD:main
